name: Build iOS IPA

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Validate project
      run: ./validate.sh
      
    - name: Build IPA
      run: ./build.sh
      
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: ChromiumIOSv2-IPA
        path: build/ChromiumIOSv2.ipa
        retention-days: 30
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/ChromiumIOSv2.ipa
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}